### ISSUE TITLE
Change the update time

### ISSUE THREAD

**Issue by rossdargan** [rossdargan/lay-z-spa-component#2]
@B-Hartley - currently it polls every 30 seconds, but that I think is excessive. I think I will change it to every one minute

**Comment by 96RadhikaJadhav** [comment]
@rossdargan Could you please assign this issue to me?

**Comment by rossdargan** [comment]
Done! Thanks for your help!

**Comment by 96RadhikaJadhav** [comment]
@rossdargan  I have created a pull request :)  Please review and let me know if any changes needs to be done.

**Comment by rossdargan** [comment]
Resolved
