### ISSUE TITLE
Error after HA Upgrade( Version 2021.1.0 / Supervisor 2020.12.7

### ISSUE THREAD

**Issue by Delta1977** [rossdargan/lay-z-spa-component#9]
After upgrade to actual HA the Component throw failure in Log and didnt working anymore:

Unable to prepare setup for platform layz_spa.water_heater: Platform not found (cannot import name 'ATTR_AWAY_MODE' from 'homeassistant.components.nest' (/usr/src/homeassistant/homeassistant/components/nest/__init__.py)).

**Comment by Delta1977** [comment]
with Commit 24ccdb55bb0a9e281e58acb9304763230db25d9f on HA Core the "ATTR_AWAY_MODE" was moved from core/homeassistant/components/nest/__init__.py   to core/homeassistant/components/nest/legacy/__init__.py .

**Comment by rossdargan** [comment]
This has been resolved. I should never have taken a dependency on that component anyway!

Thanks for reporting it.
